version: 2

defaults: &defaults
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    working_directory: ~/project
    environment:
      TF_IN_AUTOMATION: true
      
jobs:
   terraform-init:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: init
          command: terraform init -input=false
      - persist_to_workspace:
          root: ~/project/canada
          paths:
            - .
            
   terraform-plan:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project/canada
      - run:
         name: plan
         command: terraform plan -out=plan.tfplan -input=false
      - persist_to_workspace:
          root: ~/project/canada
          paths:
            - .

workflows:
   version: 2
   install-and-check-env:
     jobs:
        - terraform-init:
           filters:
             branches:
               only: main
        - terraform-plan:
           requires:
             - terraform-init
